### ISSUE TITLE
Syncpad Error During Install in Chrome

### ISSUE THREAD

**Issue by cwharts** [shatting/simplenote#20]
Package is invalid. Details: 'Could not load extension icon 'imanges/icon_96.png'.'

**Comment by JohnCPayne** [comment]
I have the same problem when trying to install syncpad.  I'm running Windows 10 Home 64bit and the latest version of Chrome.

**Comment by hansbkk** [comment]
Doesn't bode well that a simple type in the English install package hasn't gotten fixed in six months!

**Comment by VonKavalier** [comment]
Still not fixed.. Is it left dead ?

**Comment by rzbor** [comment]
Still not fixed.. Fu**ing iman_~g~_es during install...  

![imanges](https://cloud.githubusercontent.com/assets/12058524/22549756/f9eb0766-e95d-11e6-960e-a120b72f4398.png)

**Comment by TomCelestin** [comment]
Use this one instead, a guy took the abandonned project and updated it : https://chrome.google.com/webstore/detail/syncpad-for-simplenote-up/pcchkpddpepanbahfbdhcnmfbkanibog

**Comment by rzbor** [comment]
Thanks!
